version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
      - ./share:/usr/share/nginx/html

  node:
    build: ./node
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
      - "9222:9222"
    tty: true
